#! /bin/sh

pylint \
    --disable=C0103 \
    --disable=C0111 \
    --disable=C0121 \
    --disable=R0902 \
    --disable=R0912 \
    --disable=R0915 \
    --disable=W0122 \
    --disable=W0704 \
    --reports=n \
    maildirproc 2>&1 |
    grep -v "No config file found, using default configuration"
