#! /bin/sh

pylint \
    --disable-msg=C0103 \
    --disable-msg=C0111 \
    --disable-msg=C0121 \
    --disable-msg=R0902 \
    --disable-msg=R0912 \
    --disable-msg=R0915 \
    --disable-msg=W0122 \
    --disable-msg=W0704 \
    --include-ids=y \
    --reports=n \
    maildirproc 2>&1 |
    grep -v "No config file found, using default configuration"
